### Create a new user
POST http://localhost:3000/users
content-type: application/json

{
    "email": "test05@exemple.com",
    "password": "password123!"
}


### Find all users with a given email
GET http://localhost:3000/users?email=test@exemple.com


### Find a user with a given id
GET http://localhost:3000/users/3


### Update a user
PATCH http://localhost:3000/users/3
content-type: application/json

{
    "email": "user@domain.net"
}

### Delete a user with a given id
DELETE http://localhost:3000/users/1
